server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 39.106.72.96
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health