server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 3127.0.0.1:8848 #配置nacos地址
#        换成nginx的80端口，做集群
        server-addr: 39.106.72.96:80
management:
  endpoints:
    web:
      exposure:
        include: '*'