server:
  port: 8803

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的RabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于 bindings 整合
          type: rabbit # 消息组件类型
          environment:
            spring:
              rabbitmq:
                host: 39.106.72.96
                port: 5672
                username: guest
                password: guest
      bindings:  #服务整合处理
        input: # 这个名字是一个通道的名
          destination: studyExchange # 表示要使用的Exchange 名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则可以设置为"text/plain"
          default-binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: tian
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的间隔时间（默认为30秒）
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认为90秒）
    instance-id: receive-8803.com # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为ip地址