server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 39.106.72.96
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health