server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进服务中心eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MingshuWu/springcloud-config.git #github 上面git仓库名
#          搜索目录
          search-paths:
            - springcloud-config
#     读取分支
      label: master
# rabbitmq相关配置
  rabbitmq:
    host: 39.106.72.96
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
