server:
  port: 84

spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
#        配置sentinel dashboard地址
        dashboard: localhost:8080
#        默认8719，假如被占用会自动从8719开始依次+1扫描，知道找到未被占用的端口
        port: 8719

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider

# 消费者将要去访问微服务名称（注册成功进nacos的微服务提供者）
feign:
  hystrix:
    enabled: true