server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由ID，没有固定规则，但要求唯一，建议使用配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址 （固定地址，discovery.locator.enabled为 false前）
#          lb: 表示负载均衡   原本负载均衡在order端的 RestTemplate 使用@LoadBalanced
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route #路由ID，没有固定规则，但要求唯一，建议使用配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址 （固定地址，discovery.locator.enabled为 false前）
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
#            - After=2020-07-20T12:02:21.444+08:00[Asia/Shanghai] #指定时间后才能访问，不然Whitelabel Error Page，可以使用ZonedDateTime.now()获取时间格式
#            - Before=2021-07-20T12:02:21.444+08:00[Asia/Shanghai] #指定时间后才能访问，不然Whitelabel Error Page，可以使用ZonedDateTime.now()获取时间格式
#            - Between=2020-07-20T12:02:21.444+08:00[Asia/Shanghai],2021-07-20T12:02:21.444+08:00[Asia/Shanghai]
#            - Cookie=username,wutian # curl请求命令为 curl http://localhost:9527/payment/lb --cookie "username=wutian"
#            curl http://localhost:9527/payment/lb -H "X-Request-Id:10"
#            - Header=X-Request-Id, \d+ #请求头要有 X-Request-Id 属性，并且其值为整数的正则表达式
#            - Host=www.wutian.fun # curl http://localhost:9527/payment/lb -H "Host:www.wutian.fun"
#            - Method=Get #get方式可以请求，post不允许请求
#            - Query=username, \d+ #参数名为username，并且其值还要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
